### PR TITLE
Add charter

### LINKED ISSUE #1: Add charter from OpenSSF
As part of gittuf joining the OpenSSF sandbox, we are working on a formal charter for the project that includes a governance model.

See: https://github.com/gittuf/gittuf/issues/128

### PR DESCRIPTION
**Pull request by adityasaky**
Fixes #1

### CODE REVIEW

**Comment by adityasaky** [comment]
This PR adds the charter text for gittuf originally proposed in https://github.com/gittuf/gittuf/issues/128.

@JustinCappos, @wlynch, @reza-curtmola, and @mlieberman85: As gittuf TSC members, please review this draft and suggest any changes you think are necessary. When we're ready to vote, I propose we simply approve this PR (I'll leave a comment as I opened it).

Once the charter is approved, I'll submit a commit updating the "adopted" date and we should be good to merge.

**Comment by JustinCappos** [comment]
I approve!

**Review by reza-curtmola — APPROVED** [review]

**Review by mlieberman85 — APPROVED** [review]
Lgtm

**Review by wlynch — APPROVED** [review]

**Comment by adityasaky** [comment]
I approve as well!

**Pull request merged**
